### ISSUE TITLE
Can't reproduce the results of the *FAPAT* paper.

### ISSUE THREAD

**Issue by TueVNguyen** [HKUST-KnowComp/FAPAT#1]
I'm very interested with their results on session based recommendation, and I have been trying to reproduce this results.
But after correct all of the pipeline in the mining datasets (I.e run your scripts,...) and training the model by your command
1. CUDA_VISIBLE_DEVICES=1 python train.py --batch_size 200 --dataset Tmall --n_iter 1 --mem_size 12 --batch_size 200 --seed 2022 --prepad --model fapat --attributes brand category 
2. 
CUDA_VISIBLE_DEVICES=1 python eval.py --batch_size 200 --dataset Tmall --n_iter 1 --mem_size 12 --batch_size 200 --seed 2022 --prepad --model fapat --attributes brand category
The results in the Tsmall is very bad and so far with your result in paper.

So Can you give me more detailed about the arg or parmeter config in the best model for each dataset.
It will help me alot of when research on this topic.
Thanks

**Comment by seanliu96** [comment]
I am sorry for my late reply. After checking the previous running logs, I found the best parameter combinations:

*Tmall*
- batch_size: 200
- n_iter: 2
- mem_size: 12
- attributes: category, brand

*diginetica*
- batch_size: 500
- n_iter: 1
- mem_size: 12
- attributes: category

*beauty*
- batch_size: 1000
- n_iter: 2
- mem_size: 12
- attributes: category, color, brand, size

*books*
- batch_size: 2000
- n_iter: 2
- mem_size: 12
- attributes: category, publisher, author, genre

*electronics*
- batch_size: 8000
- n_iter: 2
- mem_size: 12
- attributes: type, category, color, brand

Feel free to contact me if you have any further questions.

Best regards

**Comment by TueVNguyen** [comment]
Thank you so much. I confirm that I can reproduce Tmall result in your paper with these config.

Close issue.

Thanks
